---
user: debian

gpg_keys:
  - https://download.docker.com/linux/debian/gpg
apt_repositories:
  - "deb [arch={{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

packages:
  - vim
  - curl
  - git
  - wget
  - htop
  - lsd
  - bat
  - cron
  - jq
  - apt-transport-https
  - ca-certificates
  - bash-completion
  - python3-dev
  - python3-setuptools
  - python3-pip
  - thefuck
  - nfs-common
  - lm-sensors

registry_hostname: docker.pve.home.lab
