---
gpg_keys:
  - https://download.docker.com/linux/debian/gpg
apt_repositories:
  - "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

packages:
  - vim
  - curl
  - git
  - wget
  - htop
  - apt-transport-https
  - ca-certificates
  - bash-completion
  - python3-dev
  - python3-setuptools
  - python3-pip
  - thefuck
  - nfs-common

resources:
  - name: lsd.deb
    url: https://github.com/lsd-rs/lsd/releases/download/0.23.1/lsd_0.23.1_amd64.deb
  - name: bat.deb
    url: https://github.com/sharkdp/bat/releases/download/v0.23.0/bat_0.23.0_amd64.deb

nfs_path: /opt/nfs