---
user: debian

gpg_keys:
  - https://download.docker.com/linux/debian/gpg
  - https://repos.influxdata.com/influxdata-archive_compat.key
apt_repositories:
  - "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
  - "deb [arch=amd64] https://repos.influxdata.com/debian stable main"

packages:
  - vim
  - curl
  - git
  - wget
  - htop
  - apt-transport-https
  - ca-certificates
  - bash-completion
  - python3-dev
  - python3-setuptools
  - python3-pip
  - thefuck
  - nfs-common
  - telegraf

resources:
  - name: lsd.deb
    url: https://github.com/lsd-rs/lsd/releases/download/0.23.1/lsd_0.23.1_amd64.deb
  - name: bat.deb
    url: https://github.com/sharkdp/bat/releases/download/v0.23.0/bat_0.23.0_amd64.deb

nfs_path: /opt/nfs

registry_hostname: docker.pve.home.lab

telegraf_url: https://influxdb.home.lab:443
telegraf_org: home
telegraf_bucket: linux_test
# telegraf_token: "telegraf-api-key"