---
user: debian

gpg_keys:
  - https://download.docker.com/linux/debian/gpg
apt_repositories:
  - "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"

packages:
  - vim
  - curl
  - git
  - wget
  - htop
  - lsd
  - cron
  - apt-transport-https
  - ca-certificates
  - bash-completion
  - python3-dev
  - python3-setuptools
  - python3-pip
  - thefuck
  - nfs-common
  - lm-sensors

resources:
  - name: bat.deb
    url: https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-musl_0.24.0_amd64.deb

registry_hostname: docker.pve.home.lab
