---
repo_url: https://github.com/f5AFfMhv/docker-compose-files.git
compose_dir: /opt/docker-compose
config_dir: "{{ compose_dir }}/config"
external_network: caddy-network

# Prometheus exporters configuration
prometheus_job:
  - target: mqtt2prometheus
    port: 9641
  - target: sonarr-exporter
    port: 9707
  - target: radarr-exporter
    port: 9708
  - target: pihole-exporter
    port: 9617
  - target: speedtest-exporter
    port: 9798
  - target: node-exporter
    port: 9100
  - target: pc.home.lab
    port: 9100

# List of compose files to run from git repository
compose_files:
  - portainer-agent.yaml
  - caddy.yaml
  - filebrowser.yaml
  - libre_speedtest.yaml
  - arr_stack.yaml
  - audiobookshelf.yaml
  - homarr.yaml
  - jellyfin.yaml
  - kavita.yaml
  - torrent.yaml
  - vaultwarden.yaml
  - youtube.yaml
  - watchtower.yaml
  - moon_server.yaml
  - mqtt.yaml
  - grafana.yaml
  - syncthing.yaml
  - gitea.yaml
  - prometheus.yaml

# Service port map for external caddy network
services:
  - name: prowlarr
    port: 9696
  - name: sonarr
    port: 8989
  - name: radarr
    port: 7878
  - name: jellyseerr
    port: 5055
  - name: audiobookshelf
    port: 80
  - name: filebrowser
    port: 8080
  - name: freshrss
    port: 80
  - name: gitea
    port: 3000
  - name: homarr
    port: 7575
  - name: jellyfin
    port: 8096
  - name: speedtest
    port: 3000
  - name: librespeed
    port: 80
  - name: kavita
    port: 5000
  - name: speedtest-tracker
    port: 80
  - name: uptime-kuma
    port: 3001
  - name: vaultwarden
    port: 80
  - name: tubesync
    port: 4848
  - name: metube
    port: 8081
  - name: grafana
    port: 3000
  - name: syncthing
    port: 8384
  - name: influxdb
    port: 8086
