---
repo_url: https://github.com/f5AFfMhv/docker-compose-files.git
compose_dir: /opt/docker-compose
config_dir: "{{ compose_dir }}/config"
external_network: caddy-network

# Prometheus exporters configuration
prometheus_job:
  # - target: mqtt2prometheus
  #   port: 9641
  - target: sonarr-exporter
    port: 9707
  - target: radarr-exporter
    port: 9708
  - target: pihole-exporter
    port: 9617
  - target: speedtest-exporter
    port: 9798
  - target: node-exporter
    port: 9100
  - target: pc.home.lab
    port: 9100
  # - target: pve.home.lab
  #   port: 9100
  # - target: srv.home.lab
  #   port: 9100

# List of compose files to run from git repository
compose_files:
  - portainer.yaml
  # - portainer-agent.yaml
  - caddy.yaml
  - filebrowser.yaml
  - libre_speedtest.yaml
  - arr_stack.yaml
  - audiobookshelf.yaml
  - jellyfin.yaml
  - torrent.yaml
  - vaultwarden.yaml
  - tubesync.yaml
  - watchtower.yaml
  - grafana.yaml
  - syncthing.yaml
  - gitea.yaml
  - prometheus.yaml
  - homepage.yaml
  - cloudflared.yaml
  - memos.yaml
  - nextcloud.yaml

# Service port map for external caddy network
services:
  - name: prowlarr
    port: 9696
  - name: sonarr
    port: 8989
  - name: radarr
    port: 7878
  - name: jellyseerr
    port: 5055
  - name: audiobookshelf
    port: 80
  - name: filebrowser
    port: 8080
  - name: freshrss
    port: 80
  - name: gitea
    port: 3000
  - name: jellyfin
    port: 8096
  - name: speedtest
    port: 3000
  - name: librespeed
    port: 80
  - name: kavita
    port: 5000
  - name: speedtest-tracker
    port: 80
  - name: uptime-kuma
    port: 3001
  - name: vaultwarden
    port: 80
  - name: tubesync
    port: 4848
  - name: metube
    port: 8081
  - name: grafana
    port: 3000
  - name: syncthing
    port: 8384
  - name: influxdb
    port: 8086
  - name: photoview
    port: 80
  - name: homepage
    port: 3000
  - name: memos
    port: 5230
  - name: nextcloud
    port: 80

cron_jobs:
  - name: Send ping to healthchecks server
    job: "/usr/bin/curl --retry 3 https://hc-ping.com/$HC_DOCKER_PING"
    minute: "*/10"
    hour: "*"
  - name: Remove unused docker images
    job: "/usr/bin/docker image prune -a -f"
    minute: "0"
    hour: "12"
