---
repo_url: https://github.com/f5AFfMhv/docker-compose-files.git
compose_dir: /opt/docker-compose
compose_files:
  # - portainer-agent-compose.yaml
  - rpi_compose_files/librespeed.yml
  # - filebrowser.yml
docker_data_base: "{{ compose_dir }}/data"