version: '3'
services:
  portainer:
    image: portainer/portainer-ee:latest
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Vilnius
    restart: always

volumes:
  portainer_data: