---
- name: Common tasks for all hosts
  gather_facts: false
  become: true
  hosts: all

  pre_tasks:
    - name: Install gpg
      ansible.builtin.apt:
        name: gnupg2
        state: present
        update_cache: true

    - name: Add an Apt signing keys
      ansible.builtin.apt_key:
        url: "{{ item }}"
        state: present
      with_items: "{{ gpg_keys }}"

    - name: Add repositories into sources list
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
      with_items: "{{ apt_repositories }}"

  tasks:
    - name: Update apt-get repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

    - name: Install required applications
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        update_cache: true

    - name: Start qemu agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true

  handlers:
