- name: Provision host to run docker containers
  gather_facts: true
  hosts: docker
  roles:
    - common
  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-compose-plugin
          - docker-compose
          - python3-docker
        state: present

    - name: Start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    # - name: Install docker-compose module
    #   ansible.builtin.pip:
    #     name: docker-compose
    #     extra_args: --break-system-packages

    - name: Create directories
      ansible.builtin.file:
        name: "{{ item }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0760"
        recurse: true
      with_items:
        - "{{ config_dir }}/caddy"
        - "{{ config_dir }}/homepage"
        - "{{ config_dir }}/prometheus/config"
        - "{{ config_dir }}/mqtt2prometheus"
        - "{{ data_dir }}/downloads"
        - "{{ data_dir }}/files"
        - "{{ data_dir }}/movies"
        - "{{ data_dir }}/music"
        - "{{ data_dir }}/podcasts"
        - "{{ data_dir }}/tvshows"
        - "{{ data_dir }}/pictures"

    - name: Create common network
      ansible.builtin.command:
        cmd: "docker network create {{ external_network }}"
      changed_when: docker_network.rc != 0
      ignore_errors: true
      register: docker_network

    - name: Create private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: "{{ config_dir }}/caddy/server.key"

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ config_dir }}/caddy/server.key"
        common_name: "*.{{ external_domain }}"
        organization_name: Home Lab
      register: csr

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: "{{ config_dir }}/caddy/server.crt"
        csr_content: "{{ csr.csr }}"
        privatekey_path: "{{ config_dir }}/caddy/server.key"
        provider: selfsigned

    - name: Create Caddyfile
      ansible.builtin.template:
        src: Caddyfile.j2
        dest: "{{ config_dir }}/caddy/Caddyfile"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0664"
      tags: docker

    - name: Create Homepage configuration files
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "{{ config_dir }}/homepage/{{ item }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0664"
      with_items:
        - bookmarks.yaml
        - services.yaml
        - settings.yaml
        - widgets.yaml
      tags: docker

    - name: Create prometheus configuration
      ansible.builtin.template:
        src: prometheus.yml.j2
        dest: "{{ config_dir }}/prometheus/config/prometheus.yml"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0664"
      tags: docker

    - name: Copy mqtt2prometheus configuration
      ansible.builtin.copy:
        src: prometheus2mqtt_config.yaml
        dest: "{{ config_dir }}/mqtt2prometheus/prometheus2mqtt_config.yaml"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0664"
      tags: docker

    - name: Clone Git repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ compose_dir }}/docker-compose-files"
        depth: 1
        force: true
        version: main
      tags: docker

    - name: Copy docker environment file
      ansible.builtin.template:
        src: docker.env.j2
        dest: "{{ compose_dir }}/docker-compose-files/.env"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0400"
      tags: docker

    - name: Change repository permissions
      ansible.builtin.file:
        path: "{{ compose_dir }}/docker-compose-files"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0760"
        recurse: true
      tags: docker

    - name: Run docker-compose up
      community.docker.docker_compose:
        project_src: "{{ compose_dir }}/docker-compose-files"
        build: true
        env_file: "{{ compose_dir }}/docker-compose-files/.env"
        files: "{{ compose_files }}"
        remove_orphans: true
      register: output
      tags: docker

    - name: Change config dir owner
      ansible.builtin.file:
        path: "{{ config_dir }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: true
      tags: docker

    - name: Change root home directory to work with z4h ssh teleportation feature
      ansible.builtin.lineinfile:
        path: /etc/passwd
        regexp: "^root:x:0:0:root:/root:/bin/bash$"
        line: "root:x:0:0:root:/home/{{ user }}:/home/{{ user }}/.local/bin/zsh"
