- name: Provision host to run docker containers
  gather_facts: true
  hosts: docker
  roles:
    - common
  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-compose-plugin
          - python3-docker
        state: present

    - name: Start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Install docker-compose module
      ansible.builtin.pip:
        name: docker-compose
        extra_args: --break-system-packages

    - name: Create directories
      ansible.builtin.file:
        name: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: "0770"
        recurse: true
      with_items:
        - "{{ compose_dir }}"
        - "{{ docker_data_base }}"
        - "{{ docker_data_base }}/caddy"

    - name: Create common network
      ansible.builtin.command:
        cmd: "docker network create {{ external_network }}"
      changed_when: docker_network.rc != 0
      ignore_errors: true
      register: docker_network

    - name: Create private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: "{{ docker_data_base }}/caddy/server.key"

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ docker_data_base }}/caddy/server.key"
        common_name: "*.{{ external_domain }}"
        organization_name: Home Lab
      register: csr

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: "{{ docker_data_base }}/caddy/server.crt"
        csr_content: "{{ csr.csr }}"
        privatekey_path: "{{ docker_data_base }}/caddy/server.key"
        provider: selfsigned

    - name: Copy docker environment file
      ansible.builtin.template:
        src: docker.env.j2
        dest: "{{ compose_dir }}/docker.env"
        owner: root
        group: root
        mode: "0400"
      tags: docker

    - name: Copy caddyfile
      ansible.builtin.template:
        src: Caddyfile.j2
        dest: "{{ docker_data_base }}/caddy/Caddyfile"
        owner: root
        group: root
        mode: "0664"
      tags: docker

    - name: Clone Git repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ compose_dir }}/git"
        depth: 1
        force: true
        version: main
      tags: docker

    - name: Run docker-compose up
      community.docker.docker_compose:
        project_src: "{{ compose_dir }}/git"
        build: true
        env_file: "{{ compose_dir }}/docker.env"
        files: "{{ compose_files }}"
      register: output
      tags: docker

    - name: Show docker-compose results
      ansible.builtin.debug:
        var: output.changed
      tags: docker
