- name: Provision host to run docker containers
  gather_facts: true
  hosts: docker-dev
  roles:
    - common
  tasks:
    - name: Install docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-compose-plugin
          - python3-docker
        state: present

    - name: Start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Install docker-compose module
      ansible.builtin.pip:
        name: docker-compose
        extra_args: --break-system-packages

    - name: Create directories
      ansible.builtin.file:
        name: "{{ item }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0760"
        recurse: true
      with_items:
        - "{{ config_dir }}/caddy"
        - "{{ data_dir }}/audiobooks"
        - "{{ data_dir }}/books"
        - "{{ data_dir }}/downloads"
        - "{{ data_dir }}/files"
        - "{{ data_dir }}/movies"
        - "{{ data_dir }}/music"
        - "{{ data_dir }}/podcasts"
        - "{{ data_dir }}/tvshows"

    - name: Create common network
      ansible.builtin.command:
        cmd: "docker network create {{ external_network }}"
      changed_when: docker_network.rc != 0
      ignore_errors: true
      register: docker_network

    - name: Create private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: "{{ config_dir }}/caddy/server.key"

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ config_dir }}/caddy/server.key"
        common_name: "*.{{ external_domain }}"
        organization_name: Home Lab
      register: csr

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: "{{ config_dir }}/caddy/server.crt"
        csr_content: "{{ csr.csr }}"
        privatekey_path: "{{ config_dir }}/caddy/server.key"
        provider: selfsigned

    - name: Copy caddyfile
      ansible.builtin.template:
        src: Caddyfile.j2
        dest: "{{ config_dir }}/caddy/Caddyfile"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0664"
      tags: docker

    - name: Change caddy config permissions
      ansible.builtin.file:
        path: "{{ config_dir }}/caddy"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0760"
        recurse: true

    - name: Clone Git repository
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ compose_dir }}/docker-compose-files"
        depth: 1
        force: true
        version: main
      tags: docker

    - name: Copy docker environment file
      ansible.builtin.template:
        src: docker.env.j2
        dest: "{{ compose_dir }}/docker-compose-files/.env"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0400"
      tags: docker

    - name: Change repository permissions
      ansible.builtin.file:
        path: "{{ compose_dir }}/docker-compose-files"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0760"
        recurse: true

    - name: Run docker-compose up
      community.docker.docker_compose:
        project_src: "{{ compose_dir }}/docker-compose-files"
        build: true
        env_file: "{{ compose_dir }}/docker-compose-files/.env"
        files: "{{ compose_files }}"
        remove_orphans: true
      register: output
      tags: docker
