---
- name: Provision NFS server
  gather_facts: true
  hosts: nfs
  roles:
    - nfs
  tags: nfs

- name: Provision K3S kubernetes cluster
  gather_facts: true
  hosts: k3s
  roles:
    - common
    - k3s
  tags: k3s
  tasks:
    - name: Finnishing tasks for cp
      when: inventory_hostname == groups.k3s_cp[0]
      block:
        - name: Deploy nfs storage class provisioner
          ansible.builtin.template:
            src: templates/nfs-storage-class.yml.j2
            dest: /var/lib/rancher/k3s/server/manifests/nfs-storage.yaml
            owner: root
            group: root
            mode: "0600"
          tags: nfs-storage

        - name: Download cluster kubeconfig from cp node
          ansible.builtin.fetch:
            src: /etc/rancher/k3s/k3s.yaml
            dest: ~/.kube/k3s.yaml
            flat: true
          tags: download_config

        - name: Get cluster status
          ansible.builtin.command:
            cmd: kubectl get nodes
          changed_when: test.rc != 0
          register: test
          tags: test_cluster

        - name: Show cluster status
          ansible.builtin.debug:
            msg: "{{ test.stdout_lines }}"
          tags: test_cluster

    - name: Change root home directory to work with z4h ssh teleportation feature
      ansible.builtin.lineinfile:
        path: /etc/passwd
        regexp: "^root:x:0:0:root:/root:/bin/bash$"
        line: "root:x:0:0:root:/home/{{ user }}:/home/{{ user }}/.local/bin/zsh"
