- name: Update all inventory Debian hosts
  gather_facts: true
  hosts: all
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
      when: ansible_distribution == 'Debian'

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
      when: ansible_distribution == 'Debian'
