- name: Sysprep proxmox servers
  gather_facts: true
  hosts: pve
  vars:
    script_path: /root
  roles:
    - common
    - prometheus.prometheus.node_exporter
  tasks:
    - name: Download scripts
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ script_path }}/{{ item.name }}"
        mode: "0740"
      with_items: "{{ scripts }}"
      tags: cron

    - name: Create env vars in crontab
      ansible.builtin.cron:
        name: "{{ item.var }}"
        env: true
        job: "{{ item.val }}"
      with_items: "{{ cron_env }}"
      tags: cron

    - name: Create cron jobs
      ansible.builtin.cron:
        name: "{{ item.name }}"
        user: root
        job: "{{ item.job }}"
        minute: "{{ item.minute }}"
        hour: "{{ item.hour }}"
      with_items: "{{ cron_jobs }}"
      tags: cron
